import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Permission from 'App/Models/Acl/Permission';

export default class extends BaseSeeder {
  public async run() {
    await Permission.createMany([
      { menuId: 1, name: 'can view dashboard', type: 'public' },
      { menuId: 2, name: 'can view system setting menu', type: 'public' },
      { menuId: 2, name: 'can view user menu', type: 'public' },
      { menuId: 2, name: 'can view user list', type: 'public' },
      { menuId: 2, name: 'can view user create', type: 'public' },
      { menuId: 2, name: 'can view user update', type: 'public' },
      { menuId: 2, name: 'can view user delete', type: 'public' },
      { menuId: 2, name: 'can view user profile', type: 'public' },
      { menuId: 2, name: 'can view user shop', type: 'public' },
      { menuId: 2, name: 'can view role menu', type: 'public' },
      { menuId: 2, name: 'can view role list', type: 'public' },
      { menuId: 2, name: 'can view role create', type: 'public' },
      { menuId: 2, name: 'can view role update', type: 'public' },
      { menuId: 2, name: 'can view role delete', type: 'public' },
      { menuId: 2, name: 'can view permission menu', type: 'private' },
      { menuId: 2, name: 'can view permission list', type: 'private' },
      { menuId: 2, name: 'can view permission create', type: 'private' },
      { menuId: 2, name: 'can view permission update', type: 'private' },
      { menuId: 2, name: 'can view permission delete', type: 'private' },
      { menuId: 3, name: 'can view menu menu', type: 'private' },
      { menuId: 3, name: 'can view menu list', type: 'private' },
      { menuId: 3, name: 'can view menu create', type: 'private' },
      { menuId: 3, name: 'can view menu update', type: 'private' },
      { menuId: 3, name: 'can view menu delete', type: 'private' },
      { menuId: 3, name: 'can view shop menu', type: 'private' },
      { menuId: 3, name: 'can view shop list', type: 'private' },
      { menuId: 3, name: 'can view shop create', type: 'private' },
      { menuId: 3, name: 'can view shop update', type: 'private' },
      { menuId: 3, name: 'can view shop delete', type: 'private' },
      { menuId: 4, name: 'can view product menu', type: 'public' },
      { menuId: 4, name: 'can view product list', type: 'public' },
      { menuId: 4, name: 'can view product create', type: 'public' },
      { menuId: 4, name: 'can view product update', type: 'public' },
      { menuId: 4, name: 'can view product delete', type: 'public' },
      { menuId: 4, name: 'can view attribute menu', type: 'public' },
      { menuId: 4, name: 'can view attribute list', type: 'public' },
      { menuId: 4, name: 'can view attribute create', type: 'public' },
      { menuId: 4, name: 'can view attribute update', type: 'public' },
      { menuId: 4, name: 'can view attribute delete', type: 'public' },
      { menuId: 4, name: 'can view categorie menu', type: 'public' },
      { menuId: 4, name: 'can view categorie list', type: 'public' },
      { menuId: 4, name: 'can view category create', type: 'public' },
      { menuId: 4, name: 'can view category update', type: 'public' },
      { menuId: 4, name: 'can view category delete', type: 'public' },
      { menuId: 4, name: 'can view variant menu', type: 'public' },
      { menuId: 4, name: 'can view variant list', type: 'public' },
      { menuId: 4, name: 'can view variant create', type: 'public' },
      { menuId: 4, name: 'can view variant update', type: 'public' },
      { menuId: 4, name: 'can view variant delete', type: 'public' },
      { menuId: 5, name: 'can view merchant menu', type: 'public' },
      { menuId: 5, name: 'can view merchant list', type: 'public' },
      { menuId: 5, name: 'can view merchant create', type: 'public' },
      { menuId: 5, name: 'can view merchant update', type: 'public' },
      { menuId: 5, name: 'can view merchant delete', type: 'public' },
      { menuId: 6, name: 'can view supplier menu', type: 'public' },
      { menuId: 6, name: 'can view supplier list', type: 'public' },
      { menuId: 6, name: 'can view supplier create', type: 'public' },
      { menuId: 6, name: 'can view supplier update', type: 'public' },
      { menuId: 6, name: 'can view supplier delete', type: 'public' },
      { menuId: 7, name: 'can view purchase menu', type: 'public' },
      { menuId: 7, name: 'can view purchase list', type: 'public' },
      { menuId: 7, name: 'can view purchase create', type: 'public' },
      { menuId: 7, name: 'can view purchase update', type: 'public' },
      { menuId: 7, name: 'can view purchase delete', type: 'public' },
    ]);
  }
}
