import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Product from 'App/Models/product/Product';

export default class extends BaseSeeder {
  public async run() {
    await Product.createMany([
      {
        shopId: 1,
        product_sku: '112233',
        title: 'Product 01',
        slug: 'product-01',
        price: 200,
        sale_price: 190,
        description: 'this is shop 01 product 01 long description',
        product_images: null,
      },
      {
        shopId: 1,
        product_sku: '223344',
        title: 'Product 02',
        slug: 'product-02',
        price: 300,
        sale_price: 290,
        description: 'this is shop 01 product 02 long description',
        product_images: null,
      },
      {
        shopId: 1,
        product_sku: '334455',
        title: 'Product 03',
        slug: 'product-03',
        price: 400,
        sale_price: 390,
        description: 'this is shop 01 product 03 long description',
        product_images: null,
      },
      {
        shopId: 2,
        product_sku: '445566',
        title: 'Product 01',
        slug: 'product-01',
        price: 200,
        sale_price: 190,
        description: 'this is shop 02 product 01 long description',
        product_images: null,
      },
      {
        shopId: 2,
        product_sku: '556677',
        title: 'Product 02',
        slug: 'product-02',
        price: 300,
        sale_price: 290,
        description: 'this is shop 02 product 02 long description',
        product_images: null,
      },
      {
        shopId: 2,
        product_sku: '667788',
        title: 'Product 03',
        slug: 'product-03',
        price: 400,
        sale_price: 390,
        description: 'this is shop 02 product 03 long description',
        product_images: null,
      },
      {
        shopId: 3,
        product_sku: '778899',
        title: 'Product 01',
        slug: 'product-01',
        price: 200,
        sale_price: 190,
        description: 'this is shop 03 product 01 long description',
        product_images: null,
      },
      {
        shopId: 3,
        product_sku: '889900',
        title: 'Product 02',
        slug: 'product-02',
        price: 300,
        sale_price: 290,
        description: 'this is shop 02 product 02 long description',
        product_images: null,
      },
      {
        shopId: 3,
        product_sku: '9900011',
        title: 'Product 03',
        slug: 'product-03',
        price: 400,
        sale_price: 390,
        description: 'this is shop 02 product 03 long description',
        product_images: null,
      },
    ]);
  }
}
