import { BaseSeeder } from '@adonisjs/lucid/seeders'
import UserProfile from '#models/user_profile'

export default class extends BaseSeeder {
  async run() {
    await UserProfile.createMany([
      {
        userId: 1,
        first_name: 'Iqbal',
        last_name: 'Hassan',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 2,
        first_name: 'Jawad',
        last_name: 'ali',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 3,
        first_name: 'shop1',
        last_name: 'Admin',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 4,
        first_name: 'shop1',
        last_name: 'user1',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 5,
        first_name: 'shop1',
        last_name: 'user2',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 6,
        first_name: 'shop2',
        last_name: 'Admin',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 7,
        first_name: 'shop2',
        last_name: 'user1',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 8,
        first_name: 'shop2',
        last_name: 'user2',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 9,
        first_name: 'shop3',
        last_name: 'Admin',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 10,
        first_name: 'shop3',
        last_name: 'user1',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
      {
        userId: 11,
        first_name: 'shop3',
        last_name: 'user2',
        phone_number: '12345678',
        address: 'DHA Phase 5',
        city: 'Lahore',
        state: 'Punjab',
        country: 'Pakistan',
        profile_picture: '/uploads/profile_picture/fpgjt6l5ub75k7pdjie3e6lc.jpg',
      },
    ])
  }
}
