import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Product from 'App/Models/product/Product';

export default class extends BaseSeeder {
  public async run() {
    await Product.createMany([
      {
        shopId: 1,
        categoryId: 1,
        product_sku: '112233',
        title: 'Product 01',
        slug: 'product-01',
        description: 'this is shop 01 product 01 long description',
        price: 100,
        regular_price: 200,
        stock_quantity: 1,
        product_images: '/uploads/products/product-01.png',
      },
      {
        shopId: 1,
        categoryId: 1,
        product_sku: '223344',
        title: 'Product 02',
        slug: 'product-02',
        description: 'this is shop 01 product 02 long description',
        price: 200,
        regular_price: 300,
        stock_quantity: 2,
        product_images: '/uploads/products/product-02.png',
      },
      {
        shopId: 1,
        categoryId: 2,
        product_sku: '334455',
        title: 'Product 03',
        slug: 'product-03',
        description: 'this is shop 01 product 03 long description',
        price: 300,
        regular_price: 400,
        stock_quantity: 3,
        product_images: '/uploads/products/product-03.png',
      },
      {
        shopId: 2,
        categoryId: 1,
        product_sku: '445566',
        title: 'Product 01',
        slug: 'product-01',
        description: 'this is shop 02 product 01 long description',
        price: 400,
        regular_price: 500,
        stock_quantity: 5,
        product_images: '/uploads/products/product-04.png',
      },
      {
        shopId: 2,
        categoryId: 2,
        product_sku: '556677',
        title: 'Product 02',
        slug: 'product-02',
        description: 'this is shop 02 product 02 long description',
        price: 500,
        regular_price: 600,
        stock_quantity: 3,
        product_images: '/uploads/products/product-05.png',
      },
      {
        shopId: 2,
        categoryId: 3,
        product_sku: '667788',
        title: 'Product 03',
        slug: 'product-03',
        description: 'this is shop 02 product 03 long description',
        price: 600,
        regular_price: 700,
        stock_quantity: 4,
        product_images: '/uploads/products/product-01.png',
      },
      {
        shopId: 3,
        categoryId: 1,
        product_sku: '778899',
        title: 'Product 01',
        slug: 'product-01',
        description: 'this is shop 03 product 01 long description',
        price: 700,
        regular_price: 800,
        stock_quantity: 2,
        product_images: '/uploads/products/product-02.png',
      },
      {
        shopId: 3,
        categoryId: 2,
        product_sku: '889900',
        title: 'Product 02',
        slug: 'product-02',
        description: 'this is shop 02 product 02 long description',
        price: 800,
        regular_price: 900,
        stock_quantity: 1,
        product_images: '/uploads/products/product-03.png',
      },
      {
        shopId: 3,
        categoryId: 3,
        product_sku: '9900011',
        title: 'Product 03',
        slug: 'product-03',
        description: 'this is shop 02 product 03 long description',
        price: 900,
        regular_price: 1000,
        stock_quantity: 0,
        stock_status: 'outofstock',
        product_images: '/uploads/products/product-04.png',
      },
    ]);
  }
}
